import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TOOLS_INPUT = ROOT / "requirements-tools.in"
TEST_INPUT = ROOT / "requirements-test.in"
TOOLS_LOCK = ROOT / "requirements-tools.txt"
TEST_LOCK = ROOT / "requirements-test.txt"
VALIDATE = ROOT / ".github" / "workflows" / "validate.yml"

TOOLS_PACKAGES = {
    "arrow",
    "attrs",
    "boto3",
    "botocore",
    "fqdn",
    "idna",
    "isoduration",
    "jmespath",
    "jsonpointer",
    "jsonschema",
    "jsonschema-specifications",
    "lark",
    "python-dateutil",
    "referencing",
    "rfc3339-validator",
    "rfc3986-validator",
    "rfc3987-syntax",
    "rpds-py",
    "s3transfer",
    "six",
    "typing-extensions",
    "tzdata",
    "uri-template",
    "urllib3",
    "webcolors",
}
TEST_ONLY_PACKAGES = {
    "boolean-py",
    "cachecontrol",
    "certifi",
    "charset-normalizer",
    "cyclonedx-python-lib",
    "defusedxml",
    "filelock",
    "iniconfig",
    "license-expression",
    "markdown-it-py",
    "mdurl",
    "msgpack",
    "packageurl-python",
    "packaging",
    "pip",
    "pip-api",
    "pip-audit",
    "pip-requirements-parser",
    "platformdirs",
    "pluggy",
    "py-serializable",
    "pygments",
    "pyparsing",
    "pytest",
    "requests",
    "rich",
    "sortedcontainers",
    "tomli",
    "tomli-w",
}

AUDIT_ARGUMENTS = (
    "--requirement requirements-tools.txt\n"
    "          --require-hashes --disable-pip --strict\n"
    "          --vulnerability-service pypi --timeout 10\n"
    "          --progress-spinner off --desc off --aliases off"
)


def requirement_blocks(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    header, separator, body = text.partition("\n\n")
    assert separator, f"{path.name} has no generated-lock header boundary: {header!r}"
    return re.split(r"\n(?=[a-zA-Z0-9])", body.strip())


def package_names(path: Path) -> set[str]:
    return {block.split("==", 1)[0] for block in requirement_blocks(path)}


def workflow_step(workflow: str, name: str) -> str:
    marker = f"      - name: {name}\n"
    _, separator, remainder = workflow.partition(marker)
    assert separator, f"workflow has no {name!r} step"
    return remainder.split("\n      - ", 1)[0]


def workflow_job(workflow: str, name: str) -> str:
    marker = f"\n  {name}:\n"
    _, separator, remainder = workflow.partition(marker)
    assert separator, f"workflow has no {name!r} job"
    next_job = re.search(r"\n  [a-z][a-z0-9-]*:\n", remainder)
    return remainder if next_job is None else remainder[: next_job.start()]


def test_reviewed_inputs_are_the_only_human_edited_requirements():
    assert TOOLS_INPUT.read_text(encoding="utf-8").splitlines() == [
        "boto3==1.40.0",
        "jsonschema[format-nongpl]==4.25.0",
        "referencing==0.37.0",
    ]
    assert TEST_INPUT.read_text(encoding="utf-8").splitlines() == [
        "-r requirements-tools.in",
        "pip-audit==2.10.1",
        "pytest==9.0.3",
    ]


def test_every_resolved_distribution_is_exact_hashed_and_binary_only():
    for lock, expected in (
        (TOOLS_LOCK, TOOLS_PACKAGES),
        (TEST_LOCK, TOOLS_PACKAGES | TEST_ONLY_PACKAGES),
    ):
        text = lock.read_text(encoding="utf-8")
        source = lock.with_suffix(".in").name
        assert text.startswith(
            "# Generated by tools/lock_tool_requirements.py --write for CPython\n"
            f"# 3.11.10 on x86-64 Linux. Edit {source}, not this file; "
            "requires uv 0.12.1.\n"
            "--require-hashes\n--only-binary :all:\n\n"
        )
        assert "git+" not in text
        assert "--editable" not in text
        blocks = requirement_blocks(lock)
        assert package_names(lock) == expected
        for block in blocks:
            assert "--hash=sha256:" in block, block.splitlines()[0]
            assert ";" not in block.splitlines()[0], block.splitlines()[0]

    tools = {block.split("==", 1)[0]: block for block in requirement_blocks(TOOLS_LOCK)}
    tests = {block.split("==", 1)[0]: block for block in requirement_blocks(TEST_LOCK)}
    for name, tool_block in tools.items():
        assert tests[name].splitlines()[0] == tool_block.splitlines()[0]
        assert set(re.findall(r"--hash=sha256:[0-9a-f]{64}", tests[name])) == set(
            re.findall(r"--hash=sha256:[0-9a-f]{64}", tool_block)
        )


def test_every_workflow_pip_install_is_locked_or_the_named_integration_subject():
    workflows = [
        path
        for path in (ROOT / ".github" / "workflows").iterdir()
        if path.suffix in {".yml", ".yaml"}
    ]
    installs = {}
    for workflow in sorted(workflows):
        text = workflow.read_text(encoding="utf-8")
        pip_installs = text.count("pip install")
        tool_lock_references = len(
            re.findall(r"(?:-r|--requirement)\s+requirements-tools\.txt", text)
        )
        test_lock_references = len(
            re.findall(r"(?:-r|--requirement)\s+requirements-test\.txt", text)
        )
        editable_subjects = text.count(
            "python -m pip install --disable-pip-version-check -e ."
        )
        if pip_installs:
            assert "--no-binary" not in text
            installs[workflow.name] = (
                pip_installs,
                tool_lock_references,
                test_lock_references,
                editable_subjects,
            )
    assert installs == {
        "moderation.yml": (1, 1, 0, 0),
        "publish-health.yml": (1, 1, 0, 0),
        "publish.yml": (1, 1, 0, 0),
        "reviewer-contract.yml": (2, 1, 0, 1),
        "source-availability.yml": (1, 1, 0, 0),
        "validate.yml": (2, 2, 1, 0),
        "whole-database-sweep.yml": (2, 2, 1, 0),
    }

    reviewer = (ROOT / ".github/workflows/reviewer-contract.yml").read_text(
        encoding="utf-8"
    )
    assert "the one explicit workflow-install exemption" in reviewer
    assert reviewer.index("Install database tool dependencies") < reviewer.index(
        "Install the reviewer integration subject"
    )
    assert reviewer.index("-e .") < reviewer.index("python -m pip check")


def test_least_authority_ci_reproduces_and_cold_installs_the_test_closure():
    workflow = VALIDATE.read_text(encoding="utf-8")
    closure_step = workflow_step(
        workflow, "Decide whether the reviewed Python runtime contracts changed"
    )
    assert "permissions:\n  contents: read" in workflow
    assert "secrets." not in workflow
    assert "astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9" in workflow
    assert 'version: "0.12.1"' in workflow
    assert "id: runtime-closure" in closure_step
    assert workflow.count("if: steps.runtime-closure.outputs.changed == 'true'") == 2
    assert (
        workflow.count("if: steps.runtime-closure.outputs.audit_changed == 'true'")
        == 1
    )
    for path in (
        "requirements-tools.in",
        "requirements-tools.txt",
        "requirements-test.in",
        "requirements-test.txt",
        "tools/lock_tool_requirements.py",
        ".github/workflows/validate.yml",
    ):
        assert path in closure_step
    assert ".github/workflows/whole-database-sweep.yml" in closure_step
    assert "audit_changed=true" in closure_step
    assert "audit_changed=false" in closure_step
    assert "python tools/lock_tool_requirements.py --check" in workflow
    assert "--require-hashes --no-deps --only-binary=:all:" in workflow
    assert "-r requirements-test.txt" in workflow
    assert "python -m pip check" in workflow
    assert "pytest==9.0.3" not in workflow
    assert "python -m venv" in workflow
    assert '"$runtime_env/bin/python" -m pip install' in workflow
    assert "--only-binary=:all: -r requirements-tools.txt" in workflow


def test_live_python_advisory_surveillance_is_bounded_and_least_authority():
    validate = VALIDATE.read_text(encoding="utf-8")
    sweep = (ROOT / ".github/workflows/whole-database-sweep.yml").read_text(
        encoding="utf-8"
    )

    assert validate.count("python -m pip_audit") == 1
    validate_step = workflow_step(
        validate, "Audit the reviewed production closure against live advisories"
    )
    validate_audit = validate_step.split("python -m pip_audit", 1)[1]
    assert validate_audit.startswith("\n          " + AUDIT_ARGUMENTS)
    assert "if: steps.runtime-closure.outputs.audit_changed == 'true'" in validate_step
    assert "timeout-minutes: 5" in validate_step

    python_job = workflow_job(sweep, "python-dependencies")
    assert "secrets." not in python_job
    assert "permissions:" not in python_job
    assert "persist-credentials: false" in python_job
    assert 'python-version: "3.11.10"' in python_job
    assert "--require-hashes --no-deps --only-binary=:all:" in python_job
    assert "-r requirements-test.txt" in python_job
    assert "python -m pip check" in python_job
    assert python_job.count("python -m pip_audit") == 1
    assert "timeout-minutes: 5" in python_job.rsplit("python -m pip_audit", 1)[
        0
    ].rsplit("- name:", 1)[1]
    assert python_job.split("python -m pip_audit", 1)[1].startswith(
        "\n          " + AUDIT_ARGUMENTS
    )

    for workflow in (validate, python_job):
        assert "--requirement requirements-tools.txt" in workflow
        assert "--requirement requirements-test.txt" not in workflow
        assert "--fix" not in workflow
        assert "--ignore-vuln" not in workflow
        assert "--vulnerability-service pypi" in workflow

    assert sweep.startswith("name: Whole-database sweep\n")
    trigger = sweep.split("\non:\n", 1)[1].split("\npermissions:\n", 1)[0]
    assert trigger == '  schedule:\n    - cron: "23 4 * * 1"\n  workflow_dispatch:\n'
    assert sweep.split("\npermissions:\n", 1)[1].split("\nconcurrency:\n", 1)[0] == (
        "  contents: read\n"
    )
    assert validate.split("\npermissions:\n", 1)[1].split("\njobs:\n", 1)[0] == (
        "  contents: read\n"
    )
