#!/usr/bin/env python3
"""Resolve or verify Database's reviewed Python runtime closures.

CI preserves the reviewed transitive versions while checking dependency and
hash consistency. ``--refresh`` updates accepted hashes without moving those
versions. Transitive version changes are promotions reviewed in the generated
lock diff produced by ``--write``.
"""

from __future__ import annotations

import argparse
import os
import stat
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PYTHON_VERSION = "3.11.10"
PYTHON_PLATFORM = "x86_64-unknown-linux-gnu"
UV_VERSION = "0.12.1"
TOOLS_LOCK = ("requirements-tools.in", "requirements-tools.txt")
TEST_LOCK = ("requirements-test.in", "requirements-test.txt")
# The test resolve is constrained by the production resolve generated first.
LOCKS = (TOOLS_LOCK, TEST_LOCK)


class LockError(RuntimeError):
    """The reviewed runtime closure cannot be reproduced exactly."""


def clean_environment() -> dict[str, str]:
    return {
        name: value
        for name, value in os.environ.items()
        if not name.startswith(("PYTHON", "UV_"))
    }


def reproduce(*, preserve_reviewed_versions: bool) -> dict[str, bytes]:
    environment = clean_environment()
    version = subprocess.check_output(
        ["uv", "--version"], env=environment, text=True
    ).strip()
    version_parts = version.split()
    if len(version_parts) < 2 or version_parts[:2] != ["uv", UV_VERSION]:
        raise LockError(f"tool locks require uv {UV_VERSION}, found {version!r}")

    expected: dict[str, bytes] = {}
    with tempfile.TemporaryDirectory(prefix="palomar-database-lock-") as temporary:
        if LOCKS != (TOOLS_LOCK, TEST_LOCK):
            raise LockError("the production lock must be resolved before the test lock")
        for source_name, lock_name in LOCKS:
            compiled = Path(temporary) / lock_name
            constraints: list[str] = []
            if preserve_reviewed_versions:
                constraints.extend(["--constraints", lock_name])
            if (source_name, lock_name) == TEST_LOCK:
                constraints.extend(
                    ["--constraints", str(Path(temporary) / TOOLS_LOCK[1])]
                )
            subprocess.run(
                [
                    "uv",
                    "pip",
                    "compile",
                    source_name,
                    *constraints,
                    "--output-file",
                    str(compiled),
                    "--generate-hashes",
                    "--only-binary",
                    ":all:",
                    "--emit-build-options",
                    "--python-version",
                    PYTHON_VERSION,
                    "--python-platform",
                    PYTHON_PLATFORM,
                    "--no-header",
                    "--no-annotate",
                    "--no-cache",
                    "--no-config",
                    "--quiet",
                ],
                cwd=ROOT,
                env=environment,
                check=True,
            )
            body = compiled.read_bytes()
            if not body.startswith(b"--only-binary :all:\n"):
                raise LockError(f"uv did not preserve binary-only mode in {lock_name}")
            banner = (
                "# Generated by tools/lock_tool_requirements.py --write for CPython\n"
                f"# {PYTHON_VERSION} on x86-64 Linux. Edit "
                f"{source_name}, not this file; requires uv {UV_VERSION}.\n"
                "--require-hashes\n"
            ).encode("ascii")
            expected[lock_name] = banner + body
    return expected


def write_locks(expected: dict[str, bytes]) -> None:
    for name, content in expected.items():
        destination = ROOT / name
        temporary_path: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                dir=ROOT, prefix=".palomar-database-lock-", delete=False
            ) as temporary:
                temporary_path = Path(temporary.name)
                temporary.write(content)
            temporary_path.chmod(0o644)
            temporary_path.replace(destination)
        finally:
            if temporary_path is not None:
                temporary_path.unlink(missing_ok=True)


def git_modes() -> dict[str, str]:
    output = subprocess.check_output(
        ["git", "ls-files", "--stage", "--", *(name for _, name in LOCKS)],
        cwd=ROOT,
        text=True,
    )
    modes: dict[str, str] = {}
    for line in output.splitlines():
        metadata, name = line.split("\t", 1)
        modes[name] = metadata.split(" ", 1)[0]
    return modes


def check_locks(expected: dict[str, bytes]) -> None:
    for name, content in expected.items():
        path = ROOT / name
        mode = path.lstat().st_mode
        if not stat.S_ISREG(mode) or mode & 0o111:
            raise LockError(f"{name} must be an ordinary non-executable file")
        if path.read_bytes() != content:
            raise LockError(
                f"{name} is stale; run tools/lock_tool_requirements.py --refresh "
                "to preserve versions, or --write to promote versions deliberately"
            )
    modes = git_modes()
    expected_modes = {name: "100644" for _, name in LOCKS}
    if modes != expected_modes:
        raise LockError(f"tool lock Git modes must be 100644, found {modes}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--check", action="store_true", help="reproduce and compare the locks")
    action.add_argument(
        "--write", action="store_true", help="resolve the inputs and replace the locks"
    )
    action.add_argument(
        "--refresh",
        action="store_true",
        help="refresh hashes while preserving every reviewed version",
    )
    arguments = parser.parse_args()
    try:
        expected = reproduce(
            preserve_reviewed_versions=arguments.check or arguments.refresh
        )
        if arguments.write or arguments.refresh:
            write_locks(expected)
        else:
            check_locks(expected)
    except (LockError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"tool lock error: {error}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
